export const WeddingBannerList = [
    {
        id: 1,
        theme: "FlowerGarden",
        image: "/banner-wedding/1.png",
        description: "Tema bunga mawar merah yang elegan.",
        badge:["elegan", "royal"],
        url:"",
        used:144,
    },
    {
        id: 2,
        theme: "Lavender",
        image: "/banner-wedding/2.png",
        description: "Tema bunga lavender yang tenang dan romantis.",
        badge:["traditional"],
        url: "/",
        used:52,
    },
    {
        id: 3,
        theme: "Sunflower",
        image: "/banner-wedding/3.png",
        description: "Tema bunga matahari yang cerah dan menyenangkan.",
        badge:["traditional", "professional"],
        url: "/",
        used:12,
    },
    {
        id: 4,
        theme: "Orchid",
        image: "/banner-wedding/4.png",
        description: "Tema bunga anggrek yang eksotis dan mewah.",
        badge:["kekinian", "romantis"],
        url: "/",
        used:38,
    },
    {
        id: 5,
        theme: "Tulip",
        image: "/banner-wedding/5.png",
        description: "Tema bunga tulip yang sederhana dan elegan.",
        badge:["elegan", "traditional"],
        url: "/",
        used:40,
    },
    {
        id: 6,
        theme: "Daisy",
        image: "/banner-wedding/6.png",
        description: "Tema bunga aster yang segar dan ceria.",
        badge:["culture", "old money"],
        url: "/",
        used:151,
    },
    {
        id: 7,
        theme: "Rose",
        image: "/banner-wedding/1.png",
        description: "Tema bunga mawar merah yang elegan.",
        badge:["elegan", "royal"],
        url: "/",
        used:119,
    },
    {
        id: 8,
        theme: "Lavender",
        image: "/banner-wedding/2.png",
        description: "Tema bunga lavender yang tenang dan romantis.",
        badge:["traditional"],
        url: "/",
        used:27,
    },
    {
        id: 9,
        theme: "Sunflower",
        image: "/banner-wedding/3.png",
        description: "Tema bunga matahari yang cerah dan menyenangkan.",
        badge:["old money", "elegan"],
        url: "/",
        used:33,
    },
    {
        id: 10,
        theme: "Orchid",
        image: "/banner-wedding/4.png",
        description: "Tema bunga anggrek yang eksotis dan mewah.",
        badge:["old money", "culture"],
        url: "/",
        used:35,
    },
    {
        id: 11,
        theme: "Tulip",
        image: "/banner-wedding/5.png",
        description: "Tema bunga tulip yang sederhana dan elegan.",
        badge:["culture", "traditional"],
        url: "/",
        used:32,
    },
    {
        id: 12,
        theme: "Daisy",
        image: "/banner-wedding/6.png",
        description: "Tema bunga aster yang segar dan ceria.",
        badge:["romance", "kekinian"],
        url: "/",
        used:48,
    }
];
